### ISSUE TITLE
Tooltip doesn't fit long names

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#1]
Some names get dropped into a new line outside of the tooltip because the name is too long. Here is an example of that happening:
![screen shot 2017-12-13 at 9 09 14 pm](https://user-images.githubusercontent.com/13565154/33976488-134a1d9e-e04a-11e7-8c70-517e6a64f73c.png)

This is what we want: 
![screen shot 2017-12-13 at 9 11 37 pm](https://user-images.githubusercontent.com/13565154/33976521-41816ef6-e04a-11e7-9325-45a64b25b3bb.png)

**Comment by jonorthwash** [comment]
I think #2 didn't fix this.  See attached screenshot:

![2017-12-13-23 38 41_001](https://user-images.githubusercontent.com/963849/33975781-d5519c14-e05e-11e7-8e5a-4b51e17c3bb0.png)

Also, it would be nice to have better documentation about this issue.  E.g,. what is found, and what is expected?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Fixed this problem. Didn't think of making the height scaleable because I thought the width would always be able to scale all the way. However, apparently if you open the tooltip at the edge of the screen, the width won't scale all the way and then drops down.
