### ISSUE TITLE
Add a way to filter points

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#25]
Currently, we have a way to filter arcs/flyers. Add a way to filter points.

- Should show all selected points and its connections

- All other points should be toggleable by the unused points checkbox

- Combinable with other filters

Uses:
- Makes it easier to see which points connect to others (a lot of the arcs intersect each other which makes it sometimes hard to see which points connect to others, especially in the Europe/Asia region)

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Need your comments on this.

**Comment by jonorthwash** [comment]
Okay, looking over it, I have these suggestions:
- Say "languages" instead of "points"
- Make the list use the entire space available.
- Think about other ways to do the reset thing?  I don't really like how it looks / is placed now.
