### ISSUE TITLE
Include entire set of Apertium pairs, not just the trimmed down version

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#26]
Currently, we use a [scraper](https://github.com/jonorthwash/Apertium-Global-PairViewer/blob/master/trimpairs.py) to trim down [these pairs](https://github.com/jonorthwash/Apertium-Global-PairViewer/blob/master/pairs.json.txt) to get the geojson files apertiumPoints and apertiumPairs.

- Expand both the apertiumPoints and apertiumPairs to incorporate all of pairs.json.txt.

- Note: The last couple of pairs in apertiumPairs.json were added in by hand and are the Ling073-Spring pairs.

**Comment by jonorthwash** [comment]
Could be solved with a scraping script.  Several similar ones already exist.

**Comment by JPJPJPOPOP** [comment]
I've rescraped new data and manually added in all the language coordinates. However, here is a list of ones that I haven't added in yet due to a range of problems from having many different origins, having the same coordinates as other languages, or just plainly not knowing where it goes.

epo
smj
smn
pes (https://en.wikipedia.org/wiki/Western_Persian)
ben
khk
sco
fkv
mhr
lat
mrj
myv
nog
olo
rup
sjo (same location as uig)
sma
snd
swa
vro
zho
zul

Things have gotten super messy though:
![screen shot 2018-01-01 at 10 20 33 pm](https://user-images.githubusercontent.com/13565154/34475567-11e9e068-ef42-11e7-950a-5dff86cbb64e.png)

**Comment by jonorthwash** [comment]
> epo

Hmm good question.  Maybe put stuff like this at the north pole or in the middle of the Atlantic or something else silly?

> smj
> smn
> sma

Have a look at the maps on [this page](https://en.wikipedia.org/wiki/Sami_languages) for these three.

> pes (https://en.wikipedia.org/wiki/Western_Persian)

Put it somewhere sensible in Iran.  Base it on [this map](http://www.parstimes.com/images/iran_people.jpg) or a similar one.

> ben

See [this map](http://www.ling.upenn.edu/~haroldfs/images/indoaryn.jpg).

> khk

Stick a point on Ulaanbaatar.

> sco

Find a point based on [this map](https://commons.wikimedia.org/wiki/File:Scots_speakers_in_the_2011_census.png).

> fkv

Choose a point based on [this map](https://www.ethnologue.com/map/DKFINO).

> mhr
> mrj

Base these two on [the map here](https://en.wikipedia.org/wiki/Mari_language#Dialects).

> lat

Just put it on the Vatican City and call it a day.  We can put `ita` somewhere else a bit.

> myv

Use [the map here](https://en.wikipedia.org/wiki/Moksha_language#Dialects).

> nog

It's defined as an area / areas in [this file](http://svn.code.sf.net/p/apertium/svn/trunk/apertium-tools/mapviewer/langdata/northcaucasus_turkic.ogr).  Choose a central point where it's spoken as a point.

> olo

See "Olonets" on [the map here](https://en.wikipedia.org/wiki/Karelian_language#Geographic_distribution).

> rup

Based on [https://commons.wikimedia.org/wiki/File:South-Balkan-Romance-languages.png](this map), I would say put the spot on Gramos.  It seems fairly central to where it's spoken.

> sjo (same location as uig)

The area on this [the map here](https://joshuaproject.net/people_groups/18721/CH) should work.  Hopefully that's not where we have `uig`???

> snd

From what I'm seeing, somewhere in certain areas of southern Pakistan, near the border with India, or maybe into India a bit, are where there are a lot of speakers of Sindhi.  Consult some maps.

> swa

Maybe somewhere near (but not in) Lake Victoria?

> vro

Choose a central point based on [the map here](https://commons.wikimedia.org/wiki/File:V%C3%B5ro_valdo_kaupa.jpg).

> zho

Maybe stick it somewhere between Wuhan and Yichang.  I think that's pretty central per [this map](https://commons.wikimedia.org/wiki/File:Map_of_sinitic_languages_cropped-en.svg).

> zul

There's a pretty good map [here](https://en.wikipedia.org/wiki/Zulu_language).  Just choose a point central to the area.

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Probably can close this by #54.

**Comment by jonorthwash** [comment]
Yes.  Your commits didn't say that it was closed, so it didn't close automatically...
