### ISSUE TITLE
Add way to locate points easily

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#28]
Create a way to be able to select a language from a list:

- Rotates the globe to the position of the selected language

- List should be searchable

- List should not be hardcoded, instead, generated from one of the json files.

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Could this be combined with the language filter? So like when a language gets selected, rotate to the position of that selected language.

**Comment by jonorthwash** [comment]
Yes—that's what I had in mind.  Note also this comment: https://github.com/jonorthwash/Apertium-Global-PairViewer/issues/31#issuecomment-353914159

**Comment by JPJPJPOPOP** [comment]
@jonorthwash How does this look?
![rotatetolang](https://user-images.githubusercontent.com/13565154/34427781-d3d70c8c-ebfa-11e7-95c3-16d0ff3612f3.gif)

**Comment by jonorthwash** [comment]
Looks great!

**Comment by jonorthwash** [comment]
In your demonstration gif, it takes a longer route than it has to in the rotation.  Why is this?
