### ISSUE TITLE
Globe and background color

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#29]
Currently, the globe is a bit bland with only two solid colors, white for land, and light blue for water.

It would be nice if the colors weren't solid but based off of some other information (terrain?).

The background is also a solid color, maybe add something related to space?

**Comment by dolphingarlic** [comment]
Kind of like a Google Earth background?

**Comment by JPJPJPOPOP** [comment]
@dolphingarlic Yeah, something like that would be nice.

**Comment by dolphingarlic** [comment]
I think something like https://bl.ocks.org/sarah37/d5d1a482e4454586e3188e325f37c994 might work

**Comment by JPJPJPOPOP** [comment]
Maybe. You could try this as well: http://bl.ocks.org/marcneuwirth/2865882

**Comment by dolphingarlic** [comment]
If it's possible to do, which would be better for the country colours: a gradient by population or a gradient by average altitude?

**Comment by dolphingarlic** [comment]
I'm thinking of using geojson since then I can get individual countries
