### ISSUE TITLE
visualisations as with the family-visualizer

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#31]
Try replicating a modal of similar to the image below that opens upon clicking a point.
![screen shot 2017-12-25 at 7 40 11 pm](https://user-images.githubusercontent.com/13565154/34346343-74aafed6-e9ab-11e7-8b6f-1278fecdfbfd.png)

The thickness of the lines represent how many stems.

**Comment by jonorthwash** [comment]
Another part of this issue: center on selected language on the map.

**Comment by JPJPJPOPOP** [comment]
Added in #63
