### ISSUE TITLE
drag-to-rotate acts weird when zoomed too close

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/Apertium-Global-PairViewer#37]
When the globe is zoomed pretty close, the globe rotates faster than the cursor / finger is dragged.

**Comment by JPJPJPOPOP** [comment]
My implementation of this basically scales the rotation sensitivity to the zoom level. However, this is a very hacky way to do this.

The "correct" way to do it can be seen here: http://bl.ocks.org/ivyywang/7c94cb5a3accd9913263
However, it is extremely messy involving quaternions and I do not understand what is exactly going. Should I try implementing this instead? @jonorthwash

**Comment by jonorthwash** [comment]
What did you end up going with?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash I did something similar to these: https://bl.ocks.org/mbostock/7ea1dde508cec6d2d95306f92642bc42
http://bl.ocks.org/tlfrd/df1f1f705c7940a6a7c0dca47041fec8

**Comment by jonorthwash** [comment]
How much of a "right way" is that?

Also, I like the colour/design there :)

**Comment by JPJPJPOPOP** [comment]
@jonorthwash It is "right" :D. The current implementation should work fine. It is not the hacky way I described above :D.

If you want to see a cool globe, look here: http://bl.ocks.org/dwtkns/4686432

**Comment by jonorthwash** [comment]
>  It is not the hacky way I described above :D.

Good!

> If you want to see a cool globe, look here: http://bl.ocks.org/dwtkns/4686432

Agreed, but it doesn't have lakes and rivers!
