### ISSUE TITLE
Rotating to point doesn't take the shortest path.

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#45]
For example:
![rotatetolang](https://user-images.githubusercontent.com/13565154/34451485-1c4d79d8-ecdc-11e7-8a9b-582c02be96a3.gif)

The globe should have rotated northwest.
[This](https://bl.ocks.org/mbostock/4183330) might help.

**Comment by MaathavanJkr** [comment]
Is this is still a bug?? I think its properly working now.

**Comment by JPJPJPOPOP** [comment]
@MaathavanJkr It is still a bug. It is a bit hard to recreate, but it still happens:
![bug](https://user-images.githubusercontent.com/13565154/70754206-7d1a7680-1ceb-11ea-9aa3-743c87db1e37.gif)
