### ISSUE TITLE
full-depth language filtering

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/Apertium-Global-PairViewer#49]
Filtering by language should have an option to follow all paths from the language, not just one level of depth.  E.g., when you click `kaz`, you get `tat`, and when you click `tat`, you get `rus`, so this option should let you get `rus` for when you click `kaz` too.

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Should it also be based on directionality? I.e, kaz is bidirectional to tat, but rus is only unidirectional to tat, so since rus is pointing into tat, should kaz still display rus?

Also, wouldn't it a lot of the time just display almost all of the connections?

**Comment by jonorthwash** [comment]
> Should it also be based on directionality?

Probably not.

> wouldn't it a lot of the time just display almost all of the connections?

A lot of the time, but not always.  Perhaps it would be useful to allow it to filter to a user-specified depth.
