### ISSUE TITLE
Zooming in and out resets position

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/Apertium-Global-PairViewer#5]
Currently if you move the globe around, then zoom in or out, the screen snaps back into its default state (although zoomed in or out).

![zoomissue](https://user-images.githubusercontent.com/13565154/34064523-766602a2-e1ae-11e7-86ad-2926ad03e28a.gif)

**Comment by jonorthwash** [comment]
I don't entirely understand this issue...

**Comment by jonorthwash** [comment]
Still seems to be an issue.

**Comment by jonorthwash** [comment]
Seems to work now.  Browser cache issue?
